global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using OA.Public.Maui.SampleApp.Helpers;
global using OA.Public.Maui.SampleApp.Models;
global using OA.Public.Maui.SampleApp.Services;
global using OA.Public.Maui.SampleApp.ViewModels;
global using OA.Public.Maui.SampleApp.Views;
global using System.Collections.ObjectModel;
global using System.Diagnostics;